### ISSUE TITLE
DataTables warning: table id=crewRoster - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

### ISSUE THREAD

**Issue by mdgarcia** [TRMN/medusa#111]
Receiving a dialog popup warning specifying the following:

DataTables warning: table id=crewRoster - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

This error occurred once when I clicked on HMS Medusa (SD-316)'s crew roster from my Service Record screen.  I cleared the dialogue box by clicking OK, and then it did not appear anymore upon successive retries.  I couldn't grab a screenshot because I wanted to see if I could duplicate it.  I thought given that this affected Table reinitialization, I would at least bring it up in case someone sees it/reports it again.

Apologies for not having more information.

**Comment by dweinerATL** [comment]
We saw this once before. If you clear your browser cache, it should go
away.

Dave

**Comment by mdgarcia** [comment]
Thanks! :)
