### ISSUE TITLE
Chapter reports should be CC'ed to Fleet/Task Force/etc. deputies

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#112]
Ticket ID 385 in Bolthole

James Sena (DCO Talbott Fleet) is asking that Fleet, Task Force, Task Group, & etc. deputies be cc'ed on chapter reports from subordinate chapters under them.

**Comment by Motye** [comment]
Not all areas have Deputy slots, or many CO's want the report directly.

**Comment by eplossl** [comment]
While not all areas have deputies, many of the higher-level echelons want/need their deputies to have the information.  The CO should still be receiving the data, but the reports should be CC'ed to the deputy (if relevant).

**Comment by dweinerATL** [comment]
Then the CO can forward it on to their deputies. We have had exactly one
request for this. No other FCO or DFCO has requested this. The "cost" to
make this selectable by echelon is to high for the limited use.
