### ISSUE TITLE
FR: Report on Triad qualification

### ISSUE THREAD

**Issue by mdgarcia** [TRMN/medusa#126]
Within BuShips, we've been charged with the development and retention of active chapters.  To that end, rather than having to click on each ship and check each CO/XO/Bosun for current exam status, would it be possible to generate a report that shows the highest exam completed for each ship, with a CSV output?  Thanks!

**Comment by dweinerATL** [comment]
That report has been available to the 1SL almost from the very start of Medusa.  Please have the acting CNO amend his current bolthole ticket to include the triad report permission

**Comment by mdgarcia** [comment]
Will do.  Thanks!
