### ISSUE TITLE
Announcements system

### ISSUE THREAD

**Issue by BenOvermyer** [TRMN/medusa#17]
The system needs to allow for announcements to be made and displayed. Announcements come in two flavors: Global and Chapter-specific.

Global announcements can only be made by individuals to be determined at a later time.

Chapter-specific announcements can only be made by the CO of a chapter.

Announcements, both global and chapter-specific, appear on a user's Dashboard when they log in. They should allow limited support for HTML.

**Comment by Motye** [comment]
Rob to document a development design for this

**Comment by dweinerATL** [comment]
No longer needed now that we have the forums, IMO.  If we find we need it later, we'll open a new feature request
