### ISSUE TITLE
MCAM and Honor Society eligibility emails from Medusa

### ISSUE THREAD

**Issue by Motye** [TRMN/medusa#180]
Michael Romero as BuTrain CoS will get the email for the MCAM.  

The message can go to cos@butrain.trmn.org.  

For the MCAM - The body of the email needs to have the following: 
                               member name, 
                               member number, and 
                               total completed courses
     - The subject line should read: "MEDUSA notification: MCAM qualification: member name"

Matt Miller via cos@sia.trmn.org will get the email for the Societies.

For the societies - The body of the email needs to have the following: 
                               member name, 
                               member number, 
                               which society they qualify for, and 
                               the average course score 
     - The subject line should read: "MEDUSA notification: <society name> qualification: member name"

**Comment by dweinerATL** [comment]
What about SWP notifications?  Do they want an individual email as each one is awarded, or a monthly email?

**Comment by Motye** [comment]
With respect to the SWP; here is the response I received.....
I imagine a monthly sweep on those since we tend to get more.  That one would be to TJ Allen at the moment, provostmarshal@sia.trmn.org

**Comment by dweinerATL** [comment]
Just to confirm -- individual emails to cos@sia.trmn.org anytime MEDUSA issues a MCAM and a monthly email for SWP to provostmarshal@sia.trmn.org

**Comment by Motye** [comment]
That is correct, based on the communications from Michael Romero today.

**Comment by dweinerATL** [comment]
@Motye, let's close this issue and get a new ticket to create the spec for the honor societes

**Comment by dweinerATL** [comment]
Closing and opening a new ticket for honor socities
