### ISSUE TITLE
Upgrade SWP from Enlisted to Officer

### ISSUE THREAD

**Issue by rmatheny** [TRMN/medusa#218]
Members SWP is not upgrading when they complete the necessary courses to upgrade from ESWP to the OSWP.

**Comment by rmatheny** [comment]
Spec completed and is on the TRMN Syno

**Comment by timberwoof** [comment]
PR: https://github.com/TRMN/medusa/pull/222

**Comment by rmatheny** [comment]
@dweinerATL I will do that in the future, my apologies!
