### ISSUE TITLE
Civilian/SFC rank corrections

### ISSUE THREAD

**Issue by dbuckalew** [TRMN/medusa#327]
The following are issues with ranks within MEDUSA that need to be corrected while we are still using the current system.

1. Add Civilian rank C-22B - Deputy Home Secretary to Special Intelligence Service and Diplomatic Corps ranks

2. Add/correct the following SFC ranks:

- C10 - Ranger Sergeant
- C13 - Ranger Lieutenant
- C14 - Ranger Captain
- C15 - Ranger Major
- C16 - Ranger Lieutenant Colonel
- C17 - Ranger Colonel
- C18 - Station Chief Ranger
- C19 - Sector Chief Ranger
- C20 - Planetary Chief Ranger
- C21 - Head Ranger

3. Correct the Following IAN Rank names:

- E8 - Hauptbootsman
- E9 - Stabsbootsman
- E10 - Oberstabsbootsman

**Comment by BenOvermyer** [comment]
This is done.
