### ISSUE TITLE
When trying to add a new user, an error message occurs

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#36]
When trying to add a new user an error message occurs.  The context of the error message indicates that it is related to the honorary flag  on the user's account.  Here's a screenshot of the error

![image](https://cloud.githubusercontent.com/assets/11776328/9798301/1ace4b64-57ce-11e5-882e-35a73ff954ab.png)

**Comment by dweinerATL** [comment]
Fix will be in next push to server
