### ISSUE TITLE
Allow sorting of member lists

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#38]
At this time, the member list for a ship has the CO, XO, and Bosun of the ship at the top of the list, and the rest of the list is sorted alphabetically by last name, as seen below:

![image](https://cloud.githubusercontent.com/assets/11776328/9798611/0b153cee-57d0-11e5-9e44-e2561d00ac82.png)

However, when working with a large ship, this is difficult to read as ranks and first names come before last names.

It is my recommendation that this be adjusted to either display the data in a table as Rank Abbreviation, Lastname, Firstname or allow sorting by Rank and/or First Name.

As an example, if Barbara Haver is a Chief Petty Officer, she might appear as:

CPO Haver, Barbara

Or, in a list like on my ship (picture above), the list could be toggled to sort the list by rank (thus gathering everyone together with others of their rank.

**Comment by dweinerATL** [comment]
Completed, will be in the next update pushed up to the server
