### ISSUE TITLE
On the chapter list, delete link does nothing

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#39]
When viewing the list of chapters, there is an edit link and a delete link for each chapter.  When the delete link is clicked, the page simply refreshes.  

It should pop up a warning window asking if the chapter should, in fact, be deleted and giving an opportunity to wholesale reassign any remaining members in that chapter to another chapter (defaulting to the holding chapters).

**Comment by dweinerATL** [comment]
The next push will have the delete icon hooked up
