### ISSUE TITLE
Adding a new chapter doesn't add it to the dropdown list for members to transfer

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#40]
When adding a new chapter to the list of chapters, the new chapter is not listed as a new place to which members may request to be transferred.  It is also not added to the list of chapters to which a member is assigned in a member record.

![image](https://cloud.githubusercontent.com/assets/11776328/9799633/71d42e6c-57d6-11e5-8032-0b93cafb126f.png)

![image](https://cloud.githubusercontent.com/assets/11776328/9799672/b737da76-57d6-11e5-8789-61ec970cc7f7.png)

![image](https://cloud.githubusercontent.com/assets/11776328/9799686/da59fee4-57d6-11e5-895e-ce6278fe2469.png)

**Comment by dweinerATL** [comment]
Until a CO is assigned, it won't show up.  However, you did find a bug, I need to add a branch selection to the create chapter dialog :)

**Comment by eplossl** [comment]
There also needs to be a way to assign the CO of the chapter.  As it currently exists, you cannot assign a member to be the CO of the chapter, since the chapter doesn't appear in the dropdown on the member record.  I guess that may be a separate bug.

**Comment by dweinerATL** [comment]
No, there is a separate process currently being developed for the commissioning of ships :)

**Comment by eplossl** [comment]
Looks like you have sorted this bug out at this time.
