### ISSUE TITLE
Users can be assigned to billets already filled by other users without warning

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#42]
When assigning a user to a billet already filled by another user, the system doesn't provide a warning or anything else:

![image](https://cloud.githubusercontent.com/assets/11776328/9799926/207a6caa-57d8-11e5-8b14-f9270a8810cd.png)

![image](https://cloud.githubusercontent.com/assets/11776328/9799948/3e855020-57d8-11e5-825c-732d69477592.png)

It also doesn't update the ship record, although given that the assignment in this case was updated in the future, this may not be wholly wrong:

![image](https://cloud.githubusercontent.com/assets/11776328/9799972/5f25f9ce-57d8-11e5-9cb2-593161c89fe1.png)

Instead, the site should provide a pop-up warning the user that they are about to make this change and ask if this is really what they meant to do.  It should then *MAKE* the changes requested.

**Comment by dweinerATL** [comment]
Those types of changes will only be allowed to very few people and there is a specific process that will be followed.  The extra time/effort to implement this is not worth the effort at this time.  We may revisit this in the future.
