### ISSUE TITLE
CO changes don't take effect

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#43]
When assigning a member to the CO slot on a ship, I would expect that, if the date of assignment is today or earlier than today, the change in position should be immediately recorded and become active.  Note that if someone else is assigned to that position, they should be removed from that position (preferably with a warning to the user making the change).

![image](https://cloud.githubusercontent.com/assets/11776328/9800102/18656ab4-57d9-11e5-9cb0-126d0964b8f9.png)

![image](https://cloud.githubusercontent.com/assets/11776328/9800113/23a7da24-57d9-11e5-8699-990221d3ac87.png)

![image](https://cloud.githubusercontent.com/assets/11776328/9800121/2e1daede-57d9-11e5-8aef-7c9b33ec59cd.png)

**Comment by dweinerATL** [comment]
Billet, chapter and branch changes made via the Change Request form are queued for approval by BuPers.  This is by design.
