### ISSUE TITLE
Needs error checking for grade when assigning officers

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#44]
When assigning an officer to a chapter record billet aboard ship (Co, XO, Bosun), error checking is not done to ensure that the member is also set to the proper rank for the size of ship.  Should a user attempt to assign a member to a chapter record billet without meeting the rank requirements for that billet, the user should receive a popup window and be asked to fix the rank, or be asked if they also intended to bump the member to the minimum required rank (and give them the ability to do so through clicking a button).

**Comment by dweinerATL** [comment]
Only BuPers will be allowed to set those billets.  We will consider that as a future enhancement

**Comment by Motye** [comment]
BuPers handles the assignments and will do the rank adjustments if needed.
