### ISSUE TITLE
Ship crew changes don't show up in BuPers change approval queue

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#45]
When creating a command change, the changes do not appear in the bupers approvals list for bupers to approve.

In bugs 40 & 41, changes were made to the command staff of the HMS Achilles.  Although these should have resulted in changes for bupers to approve, there are no approvals waiting for bupers to action.

![image](https://cloud.githubusercontent.com/assets/11776328/9800960/20708bda-57de-11e5-8547-d1e8354a823a.png)

**Comment by dweinerATL** [comment]
Changes made by BuPers (who will be the only ones allowed to make those changes via the member edit page) do not go into the queue.  There is a work flow currently being developed for command changes / ship commissioning / ship decomissioning
