### ISSUE TITLE
Error when clicking on HMSS Greenwich

### ISSUE THREAD

**Issue by Arghun** [TRMN/medusa#46]
From Ship / Chapter List, clicking on HMSS Greenwich SS-001 crashes:

![greenwich bug](https://cloud.githubusercontent.com/assets/14223199/9801893/f936af62-57ca-11e5-920f-7682e8361dae.png)

Error Exception: Undefined Index.

**Comment by Arghun** [comment]
I checked Katherine Mayhew and created my own Station command and neither had the problem, FWIW

**Comment by dweinerATL** [comment]
It was a problem with getting the rank for one of the crew members.  This has been fixed and will be in the next server update
