### ISSUE TITLE
Error message when clicking cancel

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#50]
When clicking cancel  to avoid making changes to a crewmember or myself, I get redirected to my own member information page which shows an error at the top of the page indicating that I don't have permission to view that page.

![image](https://cloud.githubusercontent.com/assets/11776328/9857107/af75b32c-5ae6-11e5-892a-21c91bc3e6d9.png)

**Comment by dweinerATL** [comment]
Clicking the cancel button will now take you back to the page you started on and will be pushed in the next update
