### ISSUE TITLE
Unable to add a picture to my record

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#51]
When editing my own record, I am unable to edit the record to add a picture.  When I did so, I got the following error page:

![image](https://cloud.githubusercontent.com/assets/11776328/9858169/2df2480e-5aed-11e5-8771-8d7fa84ccdc7.png)

**Comment by eplossl** [comment]
ErrorException thrown with message "htmlentities() expects parameter 1 to be string, array given (View: /home/forge/medusa.trmn.org/app/views/user/edit.blade.php)"

Stacktrace:
#29 ErrorException in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Support/helpers.php:527
#28 Illuminate\View\Engines\CompilerEngine:handleViewException in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#27 ErrorException in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Support/helpers.php:527
#26 Illuminate\Exception\Handler:handleError in <#unknown>:0
#25 htmlentities in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Support/helpers.php:527
#24 e in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Html/HtmlBuilder.php:339
#23 Illuminate\Html\HtmlBuilder:attributeElement in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Html/HtmlBuilder.php:320
#22 Illuminate\Html\HtmlBuilder:attributes in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Html/FormBuilder.php:245
#21 Illuminate\Html\FormBuilder:input in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Html/FormBuilder.php:283
#20 Illuminate\Html\FormBuilder:hidden in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:211
#19 Illuminate\Support\Facades\Facade:__callStatic in /home/forge/medusa.trmn.org/app/storage/views/011aec35936b4d310220c577c93f6b1e:294
#18 Smalldogs\Html5Inputs\Html5InputsFacade:hidden in /home/forge/medusa.trmn.org/app/storage/views/011aec35936b4d310220c577c93f6b1e:294
#17 include in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#16 Illuminate\View\Engines\PhpEngine:evaluatePath in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#15 Illuminate\View\Engines\CompilerEngine:get in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/View/View.php:134
#14 Illuminate\View\View:getContents in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/View/View.php:102
#13 Illuminate\View\View:renderContents in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/View/View.php:76
#12 Illuminate\View\View:render in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Http/Response.php:43
#11 Illuminate\Http\Response:setContent in /home/forge/medusa.trmn.org/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:202
#10 Symfony\Component\HttpFoundation\Response:__construct in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1501
#9 Illuminate\Routing\Router:prepareResponse in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1036
#8 Illuminate\Routing\Router:dispatchToRoute in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#7 Illuminate\Routing\Router:dispatch in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#6 Illuminate\Foundation\Application:dispatch in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#5 Illuminate\Foundation\Application:handle in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /home/forge/medusa.trmn.org/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /home/forge/medusa.trmn.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /home/forge/medusa.trmn.org/public/index.php:49

**Comment by dweinerATL** [comment]
Unable to duplicate, please re-open if it happens again
