### ISSUE TITLE
Add the ability to "flag" a user to BuPers

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#52]
It is not uncommon that bots come through and join ships.  While the captcha will definitely help prevent that, it would be nice if there were a way for the CO of a ship to look at the list of members on his or her ship and flag members to BuPers for additional review.  When clicking the button to flag a user, perhaps a popup window could come up to provide a reason (pulldown with perhaps a few options including "Invalid" and "Other", and then a text box to provide additional details) for the flag.  BuPers could then review the flag details and the member record and take appropriate action (possible actions might be marking the flag as invalid or deleting the member record).

**Comment by Motye** [comment]
Based on a recent data analysis, we have had less than 0.43% of records that have been "suspect". Of those only 3 were purged.  For the development time needed to build this, the savings is minimal and therefore not warranted at this time.
