### ISSUE TITLE
When a ship is recommissioned, it doesn't get reactivated properly

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#66]
The issue is particularly apparent when reviewing the HMS Samurai.  At this time, it has a commissioned date and a decommissioned date.  The result is that it shows as inactive on the database, rather than showing as active.  When a ship is recommissioned, it should either have the decommissioned date cleared or should be marked as active again and not therefore show up as decommissioned.

**Comment by davidweiner-df** [comment]
@eplossl Is this still an issue or has it been corrected?

**Comment by davidweiner-df** [comment]
I believe that this issue has been resolved, closing
