### ISSUE TITLE
Make a mardet Bosun position be called a "Gunny"

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#71]
Currently, in a MARDET, the senior NCO is called the Bosun.  That person should be called the Gunny or Senior NCO.

**Comment by eplossl** [comment]
This will also mean that the member should be able to have the billet of "Gunny" or "Senior NCO" or "Senior NCO/Gunny"

**Comment by dweinerATL** [comment]
There already should be a billet named "Gunny"

**Comment by davidweiner-df** [comment]
Currently live
