### ISSUE TITLE
Chapter report rework

### ISSUE THREAD

**Issue by eplossl** [TRMN/medusa#72]
Chapter reports should be redesigned to be able to get the crew data for a MARDET attached to the ship, even though those crew do not show up as members of the ship itself. Possibly also have mardet crew show up in the crew of the chapter itself, in addition to in the MARDET.

**Comment by Motye** [comment]
Superseded by enhancement #94 Mardet Report

**Comment by eplossl** [comment]
I disagree.  The chapter report doesn't show people who *ARE* attached to the ship (via the MARDET).  Yes, we need a MARDET report as well, but the CO of a ship (e.g. the Achilles) needs to be able to report on *ALL* chapter crew, even those who are also part of a MARDET.

**Comment by dweinerATL** [comment]
A MARDET, while attached to a ship, is a chapter in it's own rights. A
chapter report should not include the MARDET per discussions with the 1SL
and others
