### ISSUE TITLE
Editing a Peerage (Landed) Title causes the cancel/save buttons to dissapear

### ISSUE THREAD

**Issue by danbrandow** [TRMN/medusa#85]
Currently on medusa-dev I have edit-Peerage privs.

I am editing a Baronage already in the records, intending to upgrade it to an Earldom.
As soon as I change the Title, the cancel and save peerage buttons go away.
This does NOT happen when I change various Knighthoods from one to another (KR to QE, etc) -- only landed Peerages.

**Comment by davidweiner-df** [comment]
Corrected in initial 1.2.0 release
