### ISSUE TITLE
Changes since last login

### ISSUE THREAD

**Issue by davidweiner-df** [TRMN/medusa#95]
Bolthole Ticket #000210, 000045

Add an alert to notify CO's of changes to members of their echelon/unit and all subordinate units.

This may prove to be difficult or impossible to do

**Comment by eplossl** [comment]
This issue is tied to issue #103 and #104.  Once #103 is done, we can display updates for exams on a member's record (part of #104).  Other changes to a member's record may be harder to show, but I think the exam updates is mainly what this issue was about.

**Comment by Motye** [comment]
#103 and #104 are complete - Closing issue
